# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: requirements-txt-fixer
      - id: check-merge-conflict
      - id: debug-statements
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/WeblateOrg/locale_lint
    rev: v0.2.2
    hooks:
        - id: locale_lint
