.\"Created with GNOME Manpages Editor
.\"http://gmanedit.sourceforge.net
.\"Sergio Rua <srua@gpul.org>
.\"
.TH wammu 1 "2004-09-06" "Mobile phone manager"

.SH NAME
wammu \- program for managing entries in your mobile phone

.SH SYNOPSIS
.B wammu
.RI [ options ]
.br

.SH DESCRIPTION
This manual page explains the
.B wammu
program. This program is graphical interface for gammu.

.SH OPTIONS
Program currently does not accept any options.

.SH LICENCE
This program is licensed under GNU/GPL version 2.

.SH BUGS
Wammu shows bug when using wxGTK compiled without unicode in unicode locales.

.SH AUTHOR
Michal Cihar <michal@cihar.com>