# Wammu - Phone manager
# Copyright (c) 2003-4 Michal Cihar 
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MER- CHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA

# When support for sound will be implemented, here should be sounds
PredefinedSounds = [
        (_('Chimes high'),''),
        (_('Chimes low'),''),
        (_('Ding'),''),
        (_('TaDa'),''),
        (_('Notify'),''),
        (_('Drum'),''),
        (_('Claps'),''),
        (_('Fanfare'),''),
        (_('Chord high'),''),
        (_('Chord low'),''),
        ]

# Wanted somebody who will draw nicer icons :-)

Note = [
    '16 16 2 1', 
    'x c Black', 
    '  c None', 
    '      xx        ', 
    '      xxx  xxx  ', 
    '      xxxxxxxxx ', 
    '      xx  xx  xx', 
    '      xx        ', 
    '      xx        ', 
    '      xx        ', 
    '      xx        ', 
    '  xxxxxx        ', 
    ' xxxxxxx        ', 
    'xxxxxxxx        ', 
    'xxxxxxxx        ', 
    'x  xxxxx        ', 
    'x   xxxx        ', 
    ' x  xxx         ', 
    '  xxxx          '] 

UnknownPredefined = [
    '16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '    x      x    ', 
    '   x  xxxx  x   ', 
    '   x x    x x   ', 
    '    x     x x   ', 
    '          x x   ', 
    '         x x    ', 
    '        x x     ', 
    '       x x      ', 
    '       x x      ', 
    '       xx       ', 
    '                ', 
    '       xx       ', 
    '      xxxx      ', 
    '      x xx      ', 
    '       xx       ']

PredefinedAnimations = [
    (_("I'm ironic, flirty"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   x      x   x', 
    ' x   x    x   x ', 
    ' x    x  x    x ', 
    '  x    xx    x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am glad"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   x      x   x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am skeptic"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   xxxxx      x', 
    ' x       x    x ', 
    ' x        x   x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am sad"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x     xxxx     x', 
    ' x   x    x   x ', 
    ' x  x      x  x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("WOW"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x     xxxx     x', 
    'x    x    x    x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am crying"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x     x    x   x', 
    'x              x', 
    'x              x', 
    'x     xxxx     x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am winking"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x       xx   x ', 
    'x  xxxx  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   x      x   x', 
    ' x   xxxxxx   x ', 
    ' x            x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am laughing"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   x      x   x', 
    ' x   xxxxxx   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am indifferent"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x            x ', 
    ' x   xxxxxx   x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am in love"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxx xx xx ', 
    '   xx    x  x  x', 
    '  x       x   x ', 
    ' x         x x  ', 
    ' x  xx   xx x x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("I am confused"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx xx  ', 
    '   xx      x  x ', 
    '  x           x ', 
    ' x           x  ', 
    ' x  xx   xx    x', 
    'x   x x  x x x x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x   xxxxx    x ', 
    ' x            x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("Tongue hanging out"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x         x  x ', 
    ' x    xxxxx x x ', 
    '  x     xx   x  ', 
    '   xx     x   x ', 
    '     xxxxxxxxx  ']),
    (_("I am angry"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x x        x x ', 
    ' x  xx   xxx  x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x     xxxx     x', 
    ' x   x    x   x ', 
    ' x  x      x  x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("Wearing glases"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    'xxxxxxxxxxxxxxxx', 
    'x   xxx  xxx   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x  x      x  x ', 
    ' x   xxxxxx   x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    (_("Devil"),
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    'x    xxxxxx    x', 
    'xxxxx      xxxxx', 
    ' xx          xx ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x   xxxxxxxx   x', 
    'x   x x  x x   x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     ']),
    ]
