# Wanted somebody who will draw nicer icons :-)

Note = [
    '16 16 2 1', 
    'x c Black', 
    '  c None', 
    '      xx        ', 
    '      xxx  xxx  ', 
    '      xxxxxxxxx ', 
    '      xx  xx  xx', 
    '      xx        ', 
    '      xx        ', 
    '      xx        ', 
    '      xx        ', 
    '  xxxxxx        ', 
    ' xxxxxxx        ', 
    'xxxxxxxx        ', 
    'xxxxxxxx        ', 
    'x  xxxxx        ', 
    'x   xxxx        ', 
    ' x  xxx         ', 
    '  xxxx          '] 

UnknownPredefined = [
    '16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '    x      x    ', 
    '   x  xxxx  x   ', 
    '   x x    x x   ', 
    '    x     x x   ', 
    '          x x   ', 
    '         x x    ', 
    '        x x     ', 
    '       x x      ', 
    '       x x      ', 
    '       xx       ', 
    '                ', 
    '       xx       ', 
    '      xxxx      ', 
    '      x xx      ', 
    '       xx       ']

PredefinedAnimations = [
# I'm ironic, flirty
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   x      x   x', 
    ' x   x    x   x ', 
    ' x    x  x    x ', 
    '  x    xx    x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am glad
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   x      x   x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am skeptic
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   xxxxx      x', 
    ' x       x    x ', 
    ' x        x   x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am sad
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x     xxxx     x', 
    ' x   x    x   x ', 
    ' x  x      x  x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# WOW
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x     xxxx     x', 
    'x    x    x    x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am crying
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x     x    x   x', 
    'x              x', 
    'x              x', 
    'x     xxxx     x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am winking
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x       xx   x ', 
    'x  xxxx  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   x      x   x', 
    ' x   xxxxxx   x ', 
    ' x            x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am laughing
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x   x      x   x', 
    ' x   xxxxxx   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am indifferent
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x            x ', 
    ' x   xxxxxx   x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am in love
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxx xx xx ', 
    '   xx    x  x  x', 
    '  x       x   x ', 
    ' x         x x  ', 
    ' x  xx   xx x x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# I am confused
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx xx  ', 
    '   xx      x  x ', 
    '  x           x ', 
    ' x           x  ', 
    ' x  xx   xx    x', 
    'x   x x  x x x x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x   xxxxx    x ', 
    ' x            x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# Tongue hanging out
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x         x  x ', 
    ' x    xxxxx x x ', 
    '  x     xx   x  ', 
    '   xx     x   x ', 
    '     xxxxxxxxx  '],
# I am angry
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x x        x x ', 
    ' x  xx   xxx  x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x     xxxx     x', 
    ' x   x    x   x ', 
    ' x  x      x  x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# Wearing glases
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    '     xxxxxx     ', 
    '   xx      xx   ', 
    '  x          x  ', 
    ' x            x ', 
    'xxxxxxxxxxxxxxxx', 
    'x   xxx  xxx   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x              x', 
    'x              x', 
    ' x  x      x  x ', 
    ' x   xxxxxx   x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
# Devil
    ['16 16 2 1', 
    'x c Black', 
    '  c None', 
    'x    xxxxxx    x', 
    'xxxxx      xxxxx', 
    ' xx          xx ', 
    ' x            x ', 
    ' x  xx   xx   x ', 
    'x   x x  x x   x', 
    'x    xx   xx   x', 
    'x              x', 
    'x              x', 
    'x   xxxxxxxx   x', 
    'x   x x  x x   x', 
    ' x   x    x   x ', 
    ' x    xxxx    x ', 
    '  x          x  ', 
    '   xx      xx   ', 
    '     xxxxxx     '],
    ]
