#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:
LOCS=`ls locale/*/wammu.po | sed 's@.*/\(.*\)/[^/]*@\1@'`
xgettext \
    -d wammu \
    --msgid-bugs-address=gammu-users@lists.sourceforge.net \
    -o locale/wammu.pot \
    --language=Python \
    --add-comments=l10n \
    --add-location \
    --copyright-holder="Michal Čihař" \
    `find Wammu/  -name '*.py' | sort` wammu-configure.py wammu.py wammu_setup/msgfmt.py

ver=`python -c 'import Wammu; print Wammu.__version__'`

if [ "x$1" != "x--nopo4a" ] ; then
    ./admin/po4a
fi

for loc in $LOCS ; do
    cd locale/$loc
    msgmerge --previous -U -C ../../../gammu/locale/$loc/docs.po -C wammu.po -C ../../../gammu/locale/$loc/gammu.po -C ../../../gammu/locale/$loc/libgammu.po docs.po ../docs.pot
    cd ../..
done

sed -i '
    s/SOME DESCRIPTIVE TITLE/Wammu translation/;
    s/PACKAGE/Wammu/;
    s/(C) YEAR/(C) 2003 - '`date +%Y`'/;
    s/VERSION/'$ver'/;
    ' locale/wammu.pot

for loc in $LOCS ; do
    sed -i '
        s/SOME DESCRIPTIVE TITLE/Wammu translation/;
        s/PACKAGE/Wammu/;
        s/VERSION/'$ver'/;
        s/Project-Id-Version: Wammu [0-9.]*/Project-Id-Version: Wammu '$ver'/;
        ' locale/$loc/wammu.po
    msgmerge \
        --previous \
        -C locale/$loc/docs.po \
        -C ../gammu/locale/$loc/gammu.po \
        -C ../gammu/locale/$loc/libgammu.po \
        -C ../gammu/locale/$loc/docs.po \
        -U locale/$loc/wammu.po locale/wammu.pot
done
