#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:
LOCS=`ls locale/*/wammu.po | sed 's@.*/\(.*\)/[^/]*@\1@'`
xgettext \
    -d wammu \
    --msgid-bugs-address=michal@cihar.com \
    -o locale/wammu.pot \
    --language=Python \
    --add-comments=l10n \
    --add-location \
    --copyright-holder="Michal Čihař" \
    `find Wammu/  -name '*.py' | sort` wammu-configure.py wammu.py wammu_setup/msgfmt.py

ver=`python -c 'import Wammu; print Wammu.__version__'`
sed -i '
    s/SOME DESCRIPTIVE TITLE/Wammu translation/;
    s/PACKAGE/Wammu/;
    s/(C) YEAR/(C) 2003 - 2007/;
    s/VERSION/'$ver'/;
    ' locale/wammu.pot

for loc in $LOCS ; do
    sed -i '
        s/SOME DESCRIPTIVE TITLE/Wammu translation/;
        s/PACKAGE/Wammu/;
        s/VERSION/'$ver'/;
        s/Project-Id-Version: Wammu [0-9.]*/Project-Id-Version: Wammu '$ver'/;
        ' locale/$loc/wammu.po
    msgmerge --previous -U locale/$loc/wammu.po locale/wammu.pot
done
