#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

# Usage: make-release [branch]

version=`python -c 'import Wammu; print Wammu.__version__' | tr -d '\n'`

repo=wammu

tmp=`mktemp -dt $repo-build-XXXXXX`

cd $tmp
echo Working in $tmp
if [ "x$1" = "xbranch" ] ; then
    rel=RELEASE_`echo -n $version|tr . _`
    svn cp -m "Tag release $version" svn+ssh://mort/home/svn/$repo/trunk svn+ssh://mort/home/svn/$repo/tags/$rel
    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
else
    svn export svn+ssh://mort/home/svn/$repo/trunk $repo-$version
fi

cd $repo-$version

./setup.py sdist --formats=gztar,bztar,zip

if [ "x$1" = "xbranch" ] ; then
    ./setup.py register
fi

mv dist/* ../

wine c:\\python25\\python setup.py build --skip-deps bdist_wininst

mv dist/* ../

echo "Release is in $tmp directory"
ls -lh $tmp
