#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

# Usage: make-release [branch]

version=`python -c 'import Wammu; print Wammu.__version__' | tr -d '\n'`

repo=wammu

tmp=`mktemp -dt $repo-build-XXXXXX`

cd $tmp
echo Working in $tmp
if [ "x$1" = "xbranch" ] ; then
    rel=RELEASE_`echo -n $version|tr . _`
    svn cp -m "Tag release $version" svn+ssh://mort/home/svn/$repo/trunk svn+ssh://mort/home/svn/$repo/tags/$rel
    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
elif [ "x$1" = "x" ] ; then
    rel=trunk
    svn export svn+ssh://mort/home/svn/$repo/trunk $repo-$version
else
    version="$1"
    rel=RELEASE_`echo -n $version|tr . _`
    svn export svn+ssh://mort/home/svn/$repo/tags/$rel $repo-$version
fi

echo "Creating release $version from $rel"

cd $repo-$version

# Build source package
./setup.py sdist --formats=gztar,bztar,zip
mv dist/* ../

# Submit to PyPi
if [ "x$1" = "xbranch" ] ; then
    ./setup.py register
fi

# Build Windows Python installer
wine c:\\python25\\python setup.py build --skip-deps bdist_wininst
mv dist/* ../

rm -rf dist

# Build py2exe module
wine c:\\python25\\python setup.py build --skip-deps py2exe

# py2exe does not catch these for some reason
cp ~/.wine/drive_c/windows/system32/python25.dll dist/
cp ~/.wine/drive_c/Python25/Lib/site-packages/wx-2.8-msw-unicode/wx/*.dll dist/

# Build Windows installer
wine c:\\Program\ Files\\Inno\ Setup\ 5/\\ISCC.exe wammu.iss
mv Output/$repo-$version-setup.exe ../

# We're done
echo "Release is in $tmp directory"
ls -lh $tmp
