#!/bin/sh
# vim: expandtab sw=4 ts=4 sts=4:

if [ -z "$1" ] ; then
    echo "Usage: set-version VERSION"
    exit 1
fi

version=$1

do_replace() {
    sed "s/@VERSION@/$version/;" < $1 > $2
}

echo "Setting version to $version"

# Packaging
do_replace admin/templates/wammu.spec.in wammu.spec
do_replace admin/templates/description-pak.in description-pak
do_replace admin/templates/wammu.iss.in wammu.iss
do_replace admin/templates/wammu.nsi.in wammu.nsi

# Wammu/__init__.py
sed -i "s/__version__ = '[0-9.]*'/__version__ = '$version'/" Wammu/__init__.py

# Update ChangeLog
if ! grep -q "^$version$" ChangeLog ; then
    sed -i -e '/^two versions can be retrieved from Git.$/ a\
' -e '/^two versions can be retrieved from Git.$/ a\
'$version -e '/^two versions can be retrieved from Git.$/ a\
==== (2012-??-??)' -e '/^two versions can be retrieved from Git.$/ a\
' \
     ChangeLog
fi
