#!/bin/sh

REL=$1
if [ -z $REL ] ; then
    echo 'Usage: upload-release VERSION [DIR]'
    echo 'Must be called in directory with binaries or with path'
    exit 1
fi

if [ ! -z "$2" ] ; then
    cd "$2"
fi

sftp nijel,gammu@frs.sourceforge.net <<EOT
cd /home/frs/project/g/ga/gammu/wammu
mkdir $REL
cd $REL
put wammu-$REL.tar.bz2
put wammu-$REL.tar.gz
put wammu-$REL.zip
bye
EOT

sftp web  <<EOT
cd /srv/http/dl.cihar.com/wammu/v0/
put wammu-$REL.tar.bz2
put wammu-$REL.tar.gz
put wammu-$REL.zip
bye
EOT
